name: WeathFul
description: "A multifunctional weather app, with a beautiful design and easy to use!"

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  weather: ^3.1.1
  moon_icons: ^1.1.0
  intl: ^0.19.0
  convex_bottom_bar: ^3.2.0
  weather_icons: ^3.0.0
  iconsax: ^0.0.8
  icons_plus: ^5.0.0
  flutter_appbar: ^1.4.2
  expandable: ^5.0.1
  provider: ^6.0.5
  flutter_dotenv: ^5.2.1
  hugeicons: ^0.0.7
  dashed_circular_progress_bar: ^0.0.6
  url_launcher: ^6.3.1
  modal_bottom_sheet: ^3.0.0
  
  rive_animated_icon: ^2.0.3
  raised_buttons: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:
  assets: 
  - key.env
  - assets/images/Logo.png

  uses-material-design: true


   
  

  fonts:
  - family: RobotoMono
    fonts:
    - asset: assets/fonts/RobotoMono-VariableFont_wght.ttf

