name: flutter_learn
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  weather: ^3.1.1
  moon_icons: ^1.1.0
  intl: ^0.19.0
  convex_bottom_bar: ^3.2.0
  weather_icons: ^3.0.0
  iconsax: ^0.0.8
  icons_plus: ^5.0.0
  flutter_appbar: ^1.4.2
  expandable: ^5.0.1
  provider: ^6.0.5
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:
  assets: 
  - key.env

  uses-material-design: true


   
  

  fonts:
  - family: RobotoMono
    fonts:
    - asset: assets/fonts/RobotoMono-VariableFont_wght.ttf

